# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: &encoder_output_dim 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer:     # encoder architecture type
    normalize_before: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 3
   
# decoder related
decoder: contransformer
decoder_conf:
    conv_out_channels: [128,128,256,512]
    conv_kernel_sizes: [2,2,2,2]
    conv_layer_norm: true
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
    self_att_RPE: true
    max_relative_position: 64

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: bucket
bucket_bsize_dynamic: True # 48:18000000 #  #24:10000000
max_batch_size: 72 #48:128
bucket_length_multiplier: 1.1
bucket_batch_size: 8  #48:8

# optimization related
accum_grad: 4
grad_clip: 5
max_epoch: 40
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.0006
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 8000 #orgin best 6000

frontend: default
frontend_conf:
    win_length: 400
    hop_length: 160
    n_mels: &n_mels 80

preencoder: vggfeat
preencoder_conf:
    out_channels: [64,128]
    conv_kernel_size: [3,3]
    pooling_kernel_size: [2,2]
    num_conv_layers: [2,2]
    layer_norm: true
    input_feat_per_channel: *n_mels
    encoder_output_dim: *encoder_output_dim

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: false
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

num_workers: 6